# Generated by Django 4.1.7 on 2023-07-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nom', models.CharField(max_length=225)),
                ('prenoms', models.CharField(max_length=225)),
                ('contact', models.CharField(max_length=225)),
                ('situation_matrimoniale', models.CharField(choices=[('Celibataire', 'Celibataire'), ('Marie', 'Marié'), ('Autre', 'Autre')], max_length=225)),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=200)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('code_patient', models.CharField(blank=True, max_length=100)),
                ('status', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Constante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField(default=36)),
                ('poids', models.FloatField(default=0)),
                ('taille', models.FloatField(default=0)),
                ('pouls', models.FloatField(default=0)),
                ('tension', models.FloatField(default=0)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
