# Generated by Django 4.1.7 on 2023-07-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='genre',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], default='M', max_length=10),
        ),
    ]
