# Generated by Django 4.1.13 on 2024-01-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_boxhospitalisation_occupant_alter_constante_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='code_sero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
