# Generated by Django 4.1.7 on 2023-07-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='constante',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='mode_entree',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Urgence', 'Urgence')], default='Consultation', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
