# Generated by Django 4.1.7 on 2023-07-21 10:26

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rendezvous_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constante',
            name='details',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='antecedents',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='details',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motifs',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='details',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='details',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='details',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urgence',
            name='details',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
