# Generated by Django 4.1.7 on 2023-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_constante_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constante',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='antecedents',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motifs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urgence',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
