# Generated by Django 4.1.7 on 2023-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_consultation_mode_entree_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
