# Generated by Django 4.1.7 on 2023-07-22 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_constante_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMaladies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
                ('slug', models.CharField(blank=True, max_length=225, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='constante',
            name='frequence_respiratoire',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='constante',
            name='pression_arterielle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='constante',
            name='saturation_oxygene',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consultation',
            name='bilan_biologique',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='charge_viral',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='employeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='situation_matrimoniale',
            field=models.CharField(choices=[('Celibataire', 'Celibataire'), ('Concubinage', 'Concubinage'), ('Marie', 'Marié'), ('Divorce', 'Divorcé'), ('Veuf', 'Veuf'), ('Autre', 'Autre')], max_length=225),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
