# Generated by Django 4.1.7 on 2023-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consultation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='motifs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='mode_entree',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Urgence', 'Urgence'), ('Transfert', 'Transfert'), ('Hospitalisation', 'Hospitalisation'), ('Autre', 'Autre')], default='Consultation', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='situation_matrimoniale',
            field=models.CharField(choices=[('Celibataire', 'Celibataire'), ('Marie', 'Marié'), ('Divorce', 'Divorcé'), ('Veuf', 'Veuf'), ('Autre', 'Autre')], max_length=225),
        ),
    ]
