# Generated by Django 4.1.7 on 2023-07-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_consultation_motifs_alter_consultation_mode_entree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='antecedents',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
