# Generated by Django 4.1.7 on 2023-07-22 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chambrehospitalisation_boxhospitalisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxhospitalisation',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='core.chambrehospitalisation'),
        ),
        migrations.AlterField(
            model_name='chambrehospitalisation',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='core.unitehospitalisation'),
        ),
    ]
