# Generated by Django 4.1.7 on 2023-07-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rendezvous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='state',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
