# Generated by Django 4.1.7 on 2023-07-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_alter_rendezvous_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseRapide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('resultat', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('technique_analyse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.techniqueanalyse')),
                ('type_analyse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.typeanalyse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
