# Generated by Django 4.1.7 on 2023-07-21 10:26

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysepatient',
            name='details',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyserapide',
            name='details',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolanalyse',
            name='data',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
