# Generated by Django 4.1.7 on 2023-07-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolAnalyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('duree_month', models.PositiveIntegerField(default=1)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
