# Generated by Django 4.1.7 on 2023-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0002_alter_analysepatient_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='laboratoire')),
                ('temple', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='analysepatient',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyserapide',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='protocolanalyse',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
