# Generated by Django 4.1.7 on 2023-07-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_rendezvous_state'),
        ('laboratoire', '0003_analyse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysePatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratoire.analyse')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
