# Generated by Django 4.1.7 on 2023-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0004_analysepatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysepatient',
            name='resultat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysepatient',
            name='state',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
