# Generated by Django 4.1.7 on 2023-07-17 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_domicile_patient_alter_domicile_pays'),
        ('laboratoire', '0007_alter_analysepatient_user_alter_analyserapide_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysepatient',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.consultation'),
        ),
    ]
