# Generated by Django 4.1.7 on 2023-07-17 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0008_analysepatient_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysepatient',
            name='technique_analyse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.techniqueanalyse'),
        ),
        migrations.AddField(
            model_name='analysepatient',
            name='type_analyse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratoire.typeanalyse'),
        ),
    ]
