# Generated by Django 4.1.7 on 2023-07-23 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pharmacy.categoriemolecule')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.categoriemolecule')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('duree_month', models.PositiveIntegerField(default=1)),
                ('data', models.JSONField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('canceled', models.DateTimeField(blank=True, null=True)),
                ('molecules', models.ManyToManyField(null=True, related_name='protocols', to='pharmacy.molecule')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('famille', models.CharField(blank=True, max_length=200, null=True)),
                ('denomination', models.CharField(blank=True, max_length=200, null=True)),
                ('conditionnement', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(max_length=200)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('prix', models.PositiveIntegerField(null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.categoryproduits')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.typeproduits')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultation')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='molecule',
            name='medicaments',
            field=models.ManyToManyField(blank=True, null=True, related_name='molecules', to='pharmacy.produit'),
        ),
        migrations.CreateModel(
            name='LigneOrdonance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('regle', models.BooleanField(default=False)),
                ('ordonance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacy.ordonance')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.produit')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
