# Generated by Django 4.1.7 on 2023-07-21 10:26

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneordonance',
            name='details',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordonance',
            name='details',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
