# Generated by Django 4.1.7 on 2023-07-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_ligneordonance_details_alter_ordonance_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneordonance',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordonance',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
