# Generated by Django 4.1.7 on 2023-07-21 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_constante_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0003_alter_ligneordonance_details_alter_ordonance_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200, null=True)),
                ('medicaments', models.ManyToManyField(related_name='molecules', to='pharmacy.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('nom', models.CharField(max_length=200)),
                ('duree_month', models.PositiveIntegerField(default=1)),
                ('data', models.JSONField(blank=True, null=True)),
                ('molecules', models.ManyToManyField(related_name='protocols', to='pharmacy.molecule')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
