# Generated by Django 4.1.7 on 2023-07-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_ordonance_ligneordonance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneordonance',
            name='ordonance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacy.ordonance'),
        ),
    ]
