# Generated by Django 4.1.7 on 2023-07-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_molecule_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='medicaments',
            field=models.ManyToManyField(null=True, related_name='molecules', to='pharmacy.produit'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='molecules',
            field=models.ManyToManyField(null=True, related_name='protocols', to='pharmacy.molecule'),
        ),
    ]
