# Generated by Django 4.1.7 on 2023-07-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_molecule_medicaments_alter_protocol_molecules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
