# Generated by Django 4.1.7 on 2023-07-21 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_protocol_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMolecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='molecule',
            name='medicaments',
            field=models.ManyToManyField(blank=True, null=True, related_name='molecules', to='pharmacy.produit'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.categoriemolecule'),
        ),
    ]
