# Generated by Django 4.1.7 on 2023-07-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_categoriemolecule_alter_molecule_medicaments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriemolecule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pharmacy.categoriemolecule'),
        ),
    ]
