# Generated by Django 4.1.7 on 2023-07-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_constante_details_and_more'),
        ('pharmacy', '0008_categoriemolecule_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
    ]
