# Generated by Django 4.1.7 on 2023-07-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_protocol_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='conditionnement',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='denomination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='famille',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='canceled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='commentaire',
            field=models.TextField(blank=True, null=True),
        ),
    ]
